name: bezier_chart
description: A beautiful bezier line chart widget for flutter that is highly interactive and configurable.
version: 1.0.1
author: Aeyrium Inc. - Diego Velásquez <diego@aeyrium.com>
homepage: https://aeyrium.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

